### ISSUE TITLE
React Devtools are crashing when selecting a Component using a redux-react hook.

### ISSUE THREAD

**Issue by bdbch** [facebookincubator/redux-react-hook#34] opened 2019-02-21 23:53 UTC
I experienced crashes with my application when using the provided hooks.

When I try to inspect a component using the useMappedState hook, the application will crash with the following error:

![image](https://user-images.githubusercontent.com/6538827/53209865-2c427000-363c-11e9-9b53-4e68255c69a5.png)

![image](https://user-images.githubusercontent.com/6538827/53209879-36646e80-363c-11e9-9496-1b5ce3bc324c.png)

My code implementation for the name component:

```js
import React, { useCallback } from 'react'
import { useMappedState } from 'redux-react-hook'

const NamePreview = () => {
    const mapState = useCallback(state => ({
        name: state.name
    }), [])
    const { name } = useMappedState(mapState)

    return (
        <div>{ name }</div>
    )
}

export default NamePreview
```

looks like the devtools don't know how to interpret the value of the mapped state. Anyone else experienced issues like this?

**Comment by ianobermiller** [comment] 2019-02-22 06:12
@bvaughn are we doing something bad with this custom hook, or is there a bug in the devtools?

**Comment by smapress** [comment] 2019-02-22 13:48
I have been similar situation with this custom hook. I believe is bug into devtools. I tried use this case with other similar hooks and they same influence to devtools.

**Comment by bvaughn** [comment] 2019-02-22 15:55
Where's a repro that I can run?

If there's a bug triggered by DevTools, it's likely caused by the [`react-debug-tools` package](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js).

I would initially be suspicious of this async `useCallback` function:
![screen shot 2019-02-22 at 7 51 07 am](https://user-images.githubusercontent.com/29597/53253845-05edf600-3677-11e9-91a3-2cf17dd657ed.png)

But it looks like there is no async code in the second error stack.

Anyway. Repro please.

**Comment by bdbch** [comment] 2019-02-22 17:41
Yeah it only happens when I use the useCallback function. I thought it's in combination with the redux hooks.

**Comment by bvaughn** [comment] 2019-02-22 17:59
I'll take a look, but only if you point me at a Code Sandbox where I can reproduce the problem.

**Comment by bdbch** [comment] 2019-02-23 00:04
Here is a sandbox:
https://codesandbox.io/s/z2qok540m

Fullpage-Preview:
https://z2qok540m.codesandbox.io/

Note:
The app is not crashing itself in code sandbox because the error handler is not working as on a cra application. Check the console after inspecting an element. You'll see that you can't get the `<Dog />`'s hook data and the console will throw an error related to the useCallback.

Maybe it's something with React itself.

**Comment by bvaughn** [comment] 2019-02-23 20:56
Thanks for sharing the repro!

This is interesting. Initially, I suspected the [`react-debug-tools` package](https://github.com/facebook/react/blob/master/packages/react-debug-tools/src/ReactDebugHooks.js) because it's doing some clever things to inspect hook values. Setting breakpoints and stepping through the code now– it looks like when `react-debug-tools` is running things, the `useMappedState` hook is returning null for `derivedState` because of [this bit of code](https://github.com/facebook/react/blob/ba708fa79b3db6481b7886f9fdb6bb776d0c2fb9/packages/react-debug-tools/src/ReactDebugHooks.js#L108-L115):

```js
function useState<S>(
  initialState: (() => S) | S,
): [S, Dispatch<BasicStateAction<S>>] {
  let hook = nextHook();
  let state: S =
    hook !== null          // 👈 this isn't null
      ? hook.memoizedState // 👈 but this is
      : typeof initialState === 'function'
        ? initialState()
        : initialState;
  hookLog.push({primitive: 'State', stackError: new Error(), value: state});
  return [state, (action: BasicStateAction<S>) => {}];
}
```

I think that's because it's the _wrong type of hook_. Looks like [this call to `nextHook()`](https://github.com/facebook/react/blob/ba708fa79b3db6481b7886f9fdb6bb776d0c2fb9/packages/react-debug-tools/src/ReactDebugHooks.js#L107) is returning a hook of `_debugType: "useContext"`.  🤔This isn't right. Our expected state hook is actually the _next_ hook in the list...

The Fiber's expected sequence of hooks is: callback, context, state, ref (x3), effect

Bah! Looks like it's because [`useContext` doesn't call `nextHook()` to advance the list](https://github.com/facebook/react/blob/ba708fa79b3db6481b7886f9fdb6bb776d0c2fb9/packages/react-debug-tools/src/ReactDebugHooks.js#L92-L102).

**Comment by bdbch** [comment] 2019-02-23 21:00
Good that my code could help you figuring out the issue!

**Comment by bvaughn** [comment] 2019-02-24 17:45
This turned out to be a bit more complex than it seemed at first glance. (See https://github.com/facebook/react/pull/14940#issuecomment-466796548).) We have a couple of possible fixes. Waiting on some others to weigh in before proceeding.

**Comment by bdbch** [comment] 2019-02-25 09:59
Thanks for keeping us updated. I'll look into the other issue to see more informations!

**Comment by bvaughn** [comment] 2019-02-26 22:25
FYI the fix facebook/react/pull/14940 has landed, but won't be useful until the next React release.

**Comment by bdbch** [comment] 2019-03-05 19:30
Thank you alot @bvaughn!

**Comment by bvaughn** [comment] 2019-03-05 23:16
The fix for this issue was released with v16.8.4

**Closed** 2019-03-08 05:20 UTC

**Comment by brianclanton** [comment] 2019-03-25 23:17
I am still experiencing this issue with React v16.8.5 and redux-react-hook v3.2.1. 

Here's my hook:

```
export default function useOutsideMouseDownHider<T extends Node | null>(
    targetRef: MutableRefObject<T>,
    onOutsideClick?: () => void
) {
    useEffect(() => {
        if (targetRef.current === null || onOutsideClick === undefined) {
            return;
        }

        const handleMouseDown = (event: Event) => {
            if (
                event.target &&
                targetRef.current &&
                !targetRef.current.contains(event.target as Node)
            ) {
                onOutsideClick();
                event.stopPropagation();
            }
        };

        window.addEventListener('mousedown', handleMouseDown);

        return () => {
            window.removeEventListener('mousedown', handleMouseDown);
        };
    }, [targetRef.current, onOutsideClick]);
}
```

I'm getting an error saying that `targetRef` is null. 

@bdbch, are you no longer seeing this error after updating React?

**Comment by bvaughn** [comment] 2019-03-26 14:57
It's not clear that this is the same error we're talking about, since the code you show above accepts `useOutsideMouseDownHider` as a prop. (Seems possible that the surrounding code could be passing a `null` value?)
